services:
  fgc-home-panel:
    build: .
    container_name: fgc-home-panelius
    restart: unless-stopped
    environment:
      FGC_TIMEZONE: ${FGC_TIMEZONE:-Europe/Madrid}
      FGC_CACHE_TTL_SECONDS: ${FGC_CACHE_TTL_SECONDS:-30}
      FGC_HTTP_TIMEOUT_SECONDS: ${FGC_HTTP_TIMEOUT_SECONDS:-8}
      FGC_API_BASE_URL: ${FGC_API_BASE_URL:-https://dadesobertes.fgc.cat/api/explore/v2.1/catalog/datasets}
      FGC_LOG_LEVEL: ${FGC_LOG_LEVEL:-INFO}
      FGC_AMB_APP_ID: ${FGC_AMB_APP_ID:-5b1fdf3a}
      FGC_AMB_APP_KEY: ${FGC_AMB_APP_KEY:-}
      FGC_BUS_STOP_ID: ${FGC_BUS_STOP_ID:-107214}
    ports:
      - "${FGC_EXTERNAL_PORT:-8099}:8000"
